cost=75
factor=0.75

[[skills]]
name='Auris Nasus Oculus'
column='D'
from=0
to=16

[[skills]]
name='Duplicatus'
column='C'
from=0
to=7

[[skills]]
name='Favilludo'
column='A'
from=0
to=7

[[skills]]
name='Reflectimago'
column='B'
from=0
to=7

[[skills]]
name='Vocolimbo'
column='B'
from=0
to=7