factor=0.75

[[mks]]
name='Einfl'
cost=150

[[mks]]
name='Ele'
cost=225

[[mks]]
name='Form'
cost=150

[[mks]]
name='Heil'
cost=75

[[mks]]
name='Hell'
cost=150

[[mks]]
name='Illu'
cost=75

[[mks]]
name='Krft'
cost=150

[[mks]]
name='Limb'
cost=225

[[mks]]
name='Meta'
cost=225

[[mks]]
name='Umwt'
cost=150

[[mks]]
name='Vers'
cost=75

[[skills]]
name='Analys'
column='D'
from=2
to=10
mks=['Hell']

[[skills]]
name='Animatio'
column='B'
from=7
to=16
mks=['Tele']

[[skills]]
name='Armatrutz'
column='B'
from=0
to=7
mks=['Ele', 'Erz']

[[skills]]
name='Attributo'
column='B'
from=3
to=3
mks=['Eign']

[[skills]]
name='Auris Nasus Oculus'
column='D'
from=0
to=16
mks=['Illu']

[[skills]]
name='Axxeleratus'
column='B'
from=6
to=11
mks=['Eign']

[[skills]]
name='Balsam'
column='C'
from=3
to=5
mks=['Form', 'Heil']

[[skills]]
name='Bannbaladin'
column='B'
from=2
to=2
mks=['Einfl']

[[skills]]
name='Bewegung stoeren'
column='B'
from=3
to=3
mks=['Anti', 'Tele']

[[skills]]
name='Blitz'
column='B'
from=3
to=14
mks=['Einfl']

[[skills]]
name='Duplicatus'
column='C'
from=0
to=7
mks=['Illu']

[[skills]]
name='Favilludo'
column='A'
from=0
to=7
mks=['Illu']

[[skills]]
name='Firnlauf'
column='D'
from=3
to=3
mks=['Eign', 'Ele', 'Eis']

[[skills]]
name='Flim Flam'
column='A'
from=2
to=2
mks=['Umwt']

[[skills]]
name='Foramen'
column='A'
from=6
to=6
mks=['Hell', 'Tele']

[[skills]]
name='Gardianum'
column='D'
from=0
to=7
mks=['Anti', 'Krft', 'Meta']

[[skills]]
name='Gedankenbilder'
column='A'
from=6
to=6
mks=['Vers']

[[skills]]
name='Illu aufloessen'
column='B'
from=0
to=2
mks=['Anti', 'Illu']

[[skills]]
name='Klarum Purum'
column='D'
from=0
to=5
mks=['Form', 'Heil']

[[skills]]
name='Koerperlose Reise'
column='E'
from=2
to=5
mks=['Limb', 'Vers']

[[skills]]
name='Leib des Windes'
column='G'
from=2
to=2
mks=['Ele', 'Luft', 'Form']

[[skills]]
name='Manifesto'
column='A'
from=3
to=3
mks=['Ele']

[[skills]]
name='Motoricus'
column='A'
from=7
to=16
mks=['Tele']

[[skills]]
name='Movimento'
column='C'
from=5
to=5
mks=['Eign']

[[skills]]
name='Odem'
column='A'
from=5
to=10
mks=['Hell', 'Krft']

[[skills]]
name='Reflectimago'
column='B'
from=0
to=7
mks=['Illu']

[[skills]]
name='Sapefacta'
column='B'
from=0
to=7
mks=['Ele', 'Luft', 'Wasser', 'Tele']

[[skills]]
name='Sensibar'
column='C'
from=2
to=2
mks=['Hell']

[[skills]]
name='Transversalis'
column='D'
from=7
to=12
mks=['Limb']

[[skills]]
name='Unitatio'
column='A'
from=6
to=6
mks=['Krft', 'Vers']

[[skills]]
name='Vocolimbo'
column='B'
from=0
to=7
mks=['Illu']